INSERT INTO HEXA.CALENDAR
(SEQ, ID, TITLE, START_DATE , END_DATE , CONTENT)
VALUES((SELECT MAX(SEQ) FROM CALENDAR)+1,'appr2', 'INSERT TEST3', '2020-06-20', '2020-06-25', '인서트3');

ALTER TABLE CALENDAR DROP COLUMN CONTENT;
ALTER TABLE CALENDAR MODIFY(ID VARCHAR2(50));

DROP TABLE CALENDAR;
DELETE 

SELECT SEQ, ID, TITLE, START_DATE AS "START", END_DATE "END", CONTENT FROM CALENDAR c ;